### ISSUE TITLE
update zksync-web3

### ISSUE THREAD

**Issue by LuozhuZhang** [matter-labs/cross-chain-tutorial#7]
* problem: deploy contract but warn don't have enough balance

* reason: found through communication with the community because zksync-web3 is no longer supported

* how to fix: update zksync-web3

<img width="994" alt="Screen Shot 2022-04-12 at 19 45 33" src="https://user-images.githubusercontent.com/70309026/162954163-db825b3c-1e47-49a5-b801-aba258845766.png">

<img width="600" alt="Screen Shot 2022-04-12 at 19 50 13" src="https://user-images.githubusercontent.com/70309026/162954240-9d429324-0f64-449e-bc39-734bbc106f6d.png">

**Comment by ly0va** [comment]
Thanks, resolved by #8
